export default {
  init: '@popup/init',
  initDone: '@popup/init-done',
  setModal: '@popup/set-modal',
  createAlarm: '@popup/create-alarm',
  createAlarmDone: '@popup/create-alarm-done',
  editAlarm: '@popup/edit-alarm',
  editAlarmDone: '@popup/edit-alarm-done',
  deleteAlarm: '@popup/delete-alarm',
  deleteAlarmDone: '@popup/delete-alarm-done',
  stopAlarm: '@popup/stop-alarm',
  stopAlarmDone: '@popup/stop-alarm-done',
  stopAlarmAll: '@popup/stop-alarm-all',
  stopAlarmAllDone: '@popup/stop-alarm-all-done',
  updateAlarms: '@popup/update-alarms',
  optionsChange: '@popup/options-change',
  optionsChangeDone: '@popup/options-change-done',
};
